#!/bin/bash
#This scripts generates the proper modelling files for generating satistics
#on most likely P0 values

#This is a noise file generated by the stacking process
noise=$1
#This pulls out the bottom stokes I
stokesI=`ls  $noise | grep -o [0-9]*[.][0-9][0-9][0-9] | head -n 1`
#The minimum PI is 0.01 times the Stokes I
Pmin=`echo $stokesI/100000 | bc -l`
#The maximum PI is 0.05 times the Stokes I
Pmax=`echo 5*$Pmin | bc -l`
step=0.000001
#This series of tests will scale the step size based on the Pmin
if [ `echo "$Pmin>=0.0001" | bc -l` == 1 ]
	then
	step=0.00001
	fi
if [ `echo "$Pmin>=0.001" | bc -l` == 1 ]
	then
	step=0.0001
	fi
if [ `echo "$Pmin>=0.01" | bc -l` == 1 ]
	then
	step=0.001
	fi

#This checks to see if the model file already exists
if [ -f $noise"_varp0_0.000000_tst" ]
	then
		echo $noise"_varp0_0.000000_tst exists"
	else
		#This generates the model file with P0=0
		echo "running ./mk_stat_varp0 $noise 0 0 0"
		`./mk_stat_varp0 $noise 0 0 0` 
		fi

#This loop generates the multiple modelling files for determining the most
#likely P0
while [ $Pmax > $Pmin ]
	do
		Pminf=`printf "%8.6f" "$Pmin"`
		#This checks to see if the model file already exists
		if [ -f $noise"_varp0_"$Pminf"_tst" ]
			then
				echo $noise"_varp0_0"`echo $Pmin | grep -o [.][0-9][0-9][0-9][0-9][0-9][0-9]`"_tst exists"
				Pmin=`echo $Pmin+$step | bc`
			else
				echo "running ./mk_stat_varp0 $noise $Pmin $Pmax $step"
				`./mk_stat_varp0 $noise $Pmin $Pmax $step` 
				break
			fi
	done
